rustedbunions/core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
]

rustedbunions/crapdb/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "crapdb"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'admin/$', RedirectView.as_view(url='/admin')),
    url(r'about/$', views.about, name="about"),
    url(r'login/$', views.login, name="login"),
    url(r'forgetful/$', views.forgetful, name="forgetful"),
    url(r'searchcrap/$', views.searchcrap, name="searchcrap"),
    url(r'getpassword/$', views.getpassword, name="getpassword"),
    url(r'main/(?P<session_id>\w+)/$', views.main, name="main"),
    url(r'logout/(?P<session_id>\w+)/$', views.logout, name="logout"),
    url(r'querydb/(?P<session_id>\w+)/$', views.querydb, name="querydb"),
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
    url(r'superadmin/(?P<session_id>\w+)/$', views.super_admin_challenge_get_flag, name="superadmin"),
    url(r'brutalforce/(?P<session_id>\w+)/$', views.brutal_force_challenge_get, name="brutalforce"),
    url(r'brutalforceflag/(?P<session_id>\w+)/$', views.brutal_force_challenge_get_flag, name="brutalforceflag"),
    url(r'rot/(?P<session_id>\w+)/$', views.rot_challenge_get, name="rot"),
    url(r'rotflag/(?P<session_id>\w+)/$', views.rot_challenge_get_flag, name="rotflag"),
    url(r'paidcontent/(?P<session_id>\w+)/$', views.paid_content_challenge_get, name="paidcontent"),
    url(r'paidcontentflag/(?P<session_id>\w+)/$', views.paid_content_challenge_get_flag, name="paidcontentflag"),
    url(r'xor/(?P<session_id>\w+)/$', views.xor_challenge_get, name="xor"),
    url(r'xorflag/(?P<session_id>\w+)/$', views.xor_challenge_get_flag, name="xorflag"),
    url(r'genetic/(?P<session_id>\w+)/$', views.genetic_challenge_get, name="genetic"),
    url(r'geneticflag/(?P<session_id>\w+)/$', views.genetic_challenge_get_flag, name="geneticflag"),
    url(r'syncsession/(?P<session_id>\w+)/$', views.sync_session, name="syncsession"),
]

rustedbunions/rustedbunions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

index_view = RedirectView.as_view(url="/crapdb/", permanent=True)

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^crapdb/', include('crapdb.urls')),
    url(r'^etc/', include('traveler.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^leaderboard/', include('leaderboard.urls')),
    url(r'^admin/', admin.site.urls),
]

rustedbunions/crapdb/views.py
import sqlite3
import json

from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader

from core.challenge import NotEnoughHackerBucksError, ChallengeNotSolvedError
from core.session import Session, AuthenticatedSession, LoginSqlInjectionError
from core.views import update_hacker_bucks_from_flag, get_session, get_unauth_session, FlagAlreadyClaimedError
from core.util import is_user_data_valid, DataType
from rustedbunions import settings
from flags import FlagGenerator

FLAGS = FlagGenerator.generate_flags()

#pylint: disable=E1101

def sync_session(request, session_id):
    ret = {}
    unauth_session = get_unauth_session(request)

    try:
        # Update the unauth session with the hacker bucks and flags
        session = Session.get_session(session_id)
        unauth_session.from_other_session(session)
    except KeyError:
        pass

    ret = {"hacker_bucks": unauth_session.hacker_bucks}
    return HttpResponse(json.dumps(ret))

def index(request):
    context = {
        "unauth_session": get_unauth_session(request).to_json(),
        "index_page_source": FLAGS["index_page_source"][0],
        "index_console_output": FLAGS["index_console_output"][0]
    }

    if request.GET:
        d = request.GET.dict()
        error = d.get("error", None)

        if not is_user_data_valid(error):
            context["error"] = "Too much data"
        else:
            context["error"] = error

    template = loader.get_template('crapdb/index.html')
    return HttpResponse(template.render(context, request))

def about(request):
    context = {"unauth_session": get_unauth_session(request).to_json()}
    template = loader.get_template('crapdb/about.html')
    return HttpResponse(template.render(context, request))

def main(request, session_id):
    context = {
        "no_user_login": FLAGS["no_user_login"][0],
        "no_password_login": FLAGS["no_password_login"][0],
        "valid_creds_login": FLAGS["valid_creds_login"][0],
        "shortest_sqli": FLAGS["shortest_sqli"][0]
    }
    status, obj = get_session(session_id, error="Login failed. No session or session expired")
    if not status:
        return obj # On fail obj is a redirect
    session = obj # On success obj is the session

    context["session_id"] = session_id
    context["session"] = session.to_json()
    template = loader.get_template('crapdb/main.html')
    return HttpResponse(template.render(context, request))

def login(request):
    context = {
        "index_page_source": FLAGS["index_page_source"][0],
        "index_console_output": FLAGS["index_console_output"][0]
    }
    unauth_session = get_unauth_session(request)

    if request.POST:
        d = request.POST.dict()
        username = d.get("username", None)
        password = d.get("password", None)

        if username is not None and password is not None:
            if not is_user_data_valid(username) or not is_user_data_valid(password):
                context["error"] = "Too much data"
            else:
                try:
                    session = AuthenticatedSession.validate(request, username, password)
                    if session is not None:
                        # Update the new session with the current hacker bucks and flags
                        session.from_other_session(unauth_session)
                        return redirect("crapdb:main", session_id=session.oid)
                    else:
                        context["error"] = "Username/Password combination does not exist"
                except LoginSqlInjectionError as e:
                    context["error"] = str(e)

    context["unauth_session"] = unauth_session.to_json()
    template = loader.get_template("crapdb/index.html")
    return HttpResponse(template.render(context, request))

def logout(request, session_id):
    unauth_session = get_unauth_session(request)

    try:
        # Update the unauth session with the hacker bucks and flags
        session = Session.get_session(session_id)
        unauth_session.from_other_session(session)
    except KeyError:
        pass

    AuthenticatedSession.logout(session_id)
    return redirect("crapdb:index")

def forgetful(request):
    context = {
        "unauth_session": get_unauth_session(request).to_json(),
        "forgetful_page_source": FLAGS["forgetful_page_source"][0],
        "valid_sec_answer": FLAGS["valid_sec_answer"][0]
    }
    template = loader.get_template('crapdb/forgetful.html')
    return HttpResponse(template.render(context, request))

def getpassword(request):
    context = {
        "unauth_session": get_unauth_session(request).to_json(),
        "forgetful_page_source": FLAGS["forgetful_page_source"][0],
        "valid_sec_answer": FLAGS["valid_sec_answer"][0]
    }

    if request.POST:
        conn = sqlite3.connect(settings.CRAPDB_PATH)
        cursor = conn.cursor()

        d = request.POST.dict()
        username = d.get("username", None)
        answer = d.get("answer", None)

        if username is None or answer is None:
            context["error"] = "You must provide an answer"
        elif not is_user_data_valid(username) or not is_user_data_valid(answer):
            context["error"] = "Too much data"
        else:
            # Query that will filter out SQLi
            # because the user values are passed to execure as parameters
            no_sqli_query = ' '.join((
                "SELECT password FROM users",
                "WHERE username=? COLLATE NOCASE",
                "AND answer=?"
            ))

            # This query is suceptible to SQLi b/c user values are concatenated
            # to the string
            query = ' '.join((
                "SELECT password FROM users",
                "WHERE username='" + username + "' COLLATE NOCASE",
                "AND answer='" + answer + "'"
            ))

            context["actually_valid"] = False
            try:
                res = [x for x in cursor.execute(no_sqli_query, (username, answer))]
                if res:
                    # They got it right with no SQLi
                    context["actually_valid"] = True

                context["password"] = [x for x in cursor.execute(query)]
                if not context["password"]:
                    context["error"] = "Wrong answer"
            except Exception as e:
                context["error"] = "'{}' - {}".format(query, str(e))

        conn.close()

    template = loader.get_template("crapdb/forgetful.html")
    return HttpResponse(template.render(context, request))

def searchcrap(request):
    context = {
        "unauth_session": get_unauth_session(request).to_json(),
        "forgetful_page_source": FLAGS["forgetful_page_source"][0],
        "valid_sec_answer": FLAGS["valid_sec_answer"][0]
    }

    if request.POST:
        conn = sqlite3.connect(settings.CRAPDB_PATH)
        cursor = conn.cursor()

        d = request.POST.dict()
        username = d.get("username", None)

        if username is not None:
            if not is_user_data_valid(username):
                context["error"] = "Too much data"
            else:
                query = "SELECT username, paid, question FROM users WHERE username='" + username + "' COLLATE NOCASE"
                try:
                    context["result"] = [x for x in cursor.execute(query)]
                    if not context["result"]:
                        context["error"] = "User not found in database"
                except Exception as e:
                    context["error"] = "'{}' - {}".format(query, str(e))

        # Close the sqlite connection
        conn.close()

    template = loader.get_template("crapdb/forgetful.html")
    return HttpResponse(template.render(context, request))

def querydb(request, session_id):
    status, obj = get_session(session_id, http_response=True)
    if not status:
        return obj # HttpResponse containing error on fail

    ret = {"flags": []}

    if request.POST:
        conn = sqlite3.connect(settings.CRAPDB_PATH)
        cursor = conn.cursor()

        d = request.POST.dict()
        query = d.get("query", None)

        if query is not None:
            if not is_user_data_valid(query):
                ret["error"] = "Too much data"
            else:
                try:
                    ret["flags"] = [x for x in cursor.execute(query)]
                    if not ret["flags"]:
                        ret["error"] = "No flags found in database"
                except Exception as e:
                    ret["error"] = "'{}' - {}".format(query, str(e))

        conn.close()

    return HttpResponse(json.dumps(ret))

def checkflag(request, session_id):
    status, obj = get_session(session_id, http_response=True)
    if not status:
        return obj # HttpResponse containing error on fail
    session = obj # obj is session on success

    ret = {"hacker_bucks": session.hacker_bucks}

    if request.POST:
        d = request.POST.dict()
        flag = d.get("flag", None)

        if flag is not None:
            if not is_user_data_valid(flag, data_type=DataType.FLAG):
                ret["error"] = "Too much data"
            else:
                # Set's the session's hacker_bucks and prevents
                # getting points for the same flag more than once
                try:
                    update_hacker_bucks_from_flag(session, flag)
                    ret["hacker_bucks"] = session.hacker_bucks
                except FlagAlreadyClaimedError:
                    ret["error"] = "Already Claimed"

    return HttpResponse(json.dumps(ret))

def challenge_get(session, challenge_id):
    challenge = session.get_challenge(challenge_id)
    if challenge is None:
        raise KeyError("No challenge found with id: {}".format(challenge_id))

    # Raises exception NotEnoughHackerBucksError on fail
    session.hacker_bucks = challenge.purchase(session.hacker_bucks)
    return challenge

rustedbunions/crapdb/templates/crapdb/about.html
{% extends 'core/base.html' %}

{% block head %}
    {{ block.super }}

    {% load static %}
    <link href="{% static 'crapdb/css/about.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/unauth-navbar.css' %}" rel="stylesheet">

    <!-- Load Riot Tags -->
    <script src="{% static 'core/tags/unauth-navbar.tag.html' %}" type='riot/tag'></script>
{% endblock %}

{% block content %}
    <unauth-navbar hacker-bucks="{{ unauth_session.hacker_bucks }}"></unauth-navbar>

    {% load static %}
    <h1>About Us</h1>

    <div class="container">
        <a href="https://github.com/vix597/Ru5tedBun1ons">
            <img
                style="position: fixed; top: 0; left: 0; border: 0; z-index: 1031;"
                src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67"
                alt="Fork me on GitHub"
                data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png">
        </a>

        <div class="row">
            <div class="col-sm">
                <div class="card">
                    <img class="card-img-top" src="{% static 'crapdb/img/bunions1.steg.jpg' %}" alt="BUNION">
                    <div class="card-body">
                        <p class="card-text">
                            *.* brute force bar gcc interpreter strlen blob grep python fopen
                            endif while hack the mainframe alloc. If headers back door wombat
                            segfault tcp machine code flood. Sql stack mega error gurfle cache
                            January 1, 1970 continue giga true packet sniffer do warez foad var
                            worm Donald Knuth stack trace.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card">
                    <img class="card-img-top" src="{% static 'crapdb/img/bunions2.steg.bmp' %}" alt="BUNION">
                    <div class="card-body">
                        <p class="card-text">
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                            ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT ROT
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <div class="card">
                    <img class="card-img-top" src="{% static 'crapdb/img/bunions3.steg.png' %}" alt="BUNION">
                    <div class="card-body">
                        <p class="card-text">
                            password password password password password password password
                            password password password password password password password
                            password password password password password password password
                            password password password password password password password
                            password password password password password password password
                            password password password password password password password
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h1>About Stego</h1>

    <div class="container">
        <p>
            On an unrelated note (e.g. nothing to do with those images above) I wrote a sweet
            super secure next generation stego program that everyone should know about.
        </p>
        <p>
            Stego, short for steganography is when you hide data in other files. My next generation
            python library uses super secure stego techniques and works particularly well to hide
            data in images. Get it here: <a href="{% static 'crapdb/other/stegcrap.py.txt' %}">stegcrap.py</a>
        </p>
    </div>
{% endblock %}

{% block footer %}
    <p>&copy; {% now "Y" %} rustedbunions.com | <a href="{% url 'crapdb:index' %}">home</a></p>
{% endblock %}

{% block script %}
    {{ block.super }}

    <script>
        $(document).ready(function() {
            riot.mount("unauth-navbar");
            syncSession();
        });
    </script>
{% endblock %}

rustedbunions/crapdb/templates/crapdb/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

            <meta name="theme-color" content="#4286f4" />

            <title>C4n y0u H4ck 1t</title>

            <!-- Bootstrap CSS -->
            <link rel="stylesheet"
                href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" 
                integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" 
                crossorigin="anonymous">

            {% load static %}
            <!-- Handles the favicon -->
            <link rel="shortcut icon" type="image/png" href="{% static 'crapdb/img/favicon.ico' %}"/>

            <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
            <link rel="stylesheet" href="{% static 'core/css/ie10-viewport-bug-workaround.css' %}">

            <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}

            <footer class="footer">
                <p>&copy; {% now "Y" %} rustedbunions.com</p>
            </footer>
        </div>

        {% block script %}
            <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
            <script
                src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
                crossorigin="anonymous"></script>
            
            <!-- Popper (necessary for Bootstrap) -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
                integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
                crossorigin="anonymous"></script>

            <!-- Bootstrap Javascript -->
            <script
                src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
                integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
                crossorigin="anonymous"></script>

            <!-- RIOT JS -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/riot/3.7.3/riot+compiler.min.js" 
                integrity="sha256-GHA3LYZISL25HCo1Hu8hAxdb96gNplLLnVDsl0MKamM=" 
                crossorigin="anonymous"></script>

            {% load static %}
            <!-- Load the core JS for the site -->
            <script src="{% static 'crapdb/js/core.js' %}"></script>
        {% endblock %}
    </body>
</html>

rustedbunions/crapdb/templates/crapdb/forgetful.html
{% extends 'core/base.html' %}

{% block head %}
    {{ block.super }}

    <!-- Custom styles for signin page -->
    {% load static %}
    <link href="{% static 'crapdb/css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/unauth-navbar.css' %}" rel="stylesheet">

    <!-- Load Riot Tags -->
    <script src="{% static 'core/tags/unauth-navbar.tag.html' %}" type='riot/tag'></script>
{% endblock %}

{% block content %}
    <unauth-navbar hacker-bucks="{{ unauth_session.hacker_bucks }}"></unauth-navbar>

    <form class="form-signin" action="{% url 'crapdb:searchcrap' %}" method="POST">
        {% csrf_token %}

        <h2 class="form-signin-heading">Who are you?</h2>

        <label for="inputUsername" class="sr-only">Username</label>
        <input name="username" type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus>

        <input type="hidden" value="{{ forgetful_page_source }}">

        <div style="padding-top: 10px;">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Search</button>
            <button onclick="goBack()" class="btn btn-lg btn-primary btn-block" type="button">Back</button>
        </div>
    </form>

    {% if result %}
        <div class="alert alert-success" role="alert">
            User found
        </div>
        <form action="{% url 'crapdb:getpassword' %}" method="POST">
            {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Username</th>
                        <th scope="col">Paid User?</th>
                        <th scope="col">Security Question</th>
                        <th scope="col">Answer</th>
                        <th scope="col">Get Password</th>
                    </tr>
                </thead>
                <tbody>
                    {% for name in result %}
                        <tr>
                            <td>{{ name.0 }}</td>
                            <td>
                                {% if name.1 %}
                                    Yes
                                {% else %}
                                    No
                                {% endif %}
                            </td>
                            <td>{{ name.2 }}</td>
                            <td>
                                <input
                                    type="text"
                                    name="answer"
                                    class="form-control"
                                    placeholder="Security Question Answer"
                                    required>
                                <input type="hidden" name="username" value="{{ name.0 }}">
                            </td>
                            <td>
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Get Password</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    {% elif error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% elif password %}
        {% for pass in password %}
            <div class="alert alert-success" role="alert">
                Password: {{ pass.0 }}
            </div>
        {% endfor %}
        {% if actually_valid %}
            <div class="alert alert-success" role="alert">
                Great job getting the answer without SQLi. Here's a flag: {{ valid_sec_answer }}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

{% block script %}
    {{ block.super }}

    <script>
        function goBack() {
            window.location = "/";
        }

        $(document).ready(function() {
            riot.mount("unauth-navbar");
            syncSession();
        });
    </script>
{% endblock %}

rustedbunions/crapdb/templates/crapdb/index.html
{% extends 'core/base.html' %}

{% block head %}
    {{ block.super }}

    <!-- Custom styles for signin page -->
    {% load static %}
    <link href="{% static 'crapdb/css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/unauth-navbar.css' %}" rel="stylesheet">

    <!-- Load Riot Tags -->
    <script src="{% static 'core/tags/unauth-navbar.tag.html' %}" type='riot/tag'></script>
{% endblock %}

{% block content %}
    <unauth-navbar hacker-bucks="{{ unauth_session.hacker_bucks }}"></unauth-navbar>

    <h1 class="text-center">Welcome Spring 2019 CNY Hackathon...Good luck!</h1>

    <form autocomplete="off" class="form-signin" action="{% url 'crapdb:login' %}" method="POST">
        {% csrf_token %}
        <!-- Trying my hardest to avoid autocomplete here-->
        <input style="display:none;" autocomplete="false" type="text" name="noautocomplete">
        <input style="display:none" type="text" name="username"/>
        <input style="display:none" type="password" name="password"/>

        <h2 class="form-signin-heading">Please sign in</h2>

        <label for="inputUsername" class="sr-only">Username</label>
        <input name="username" type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus>

        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" autocomplete="new-password" type="password" id="inputPassword" maxlength="128" class="form-control" placeholder="Password" required>

        <input type="hidden" value="{{ index_page_source }}">

        <div class="checkbox">
            <label>
                <!-- Does nothing...LOL -->
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>

        <a href="{% url 'crapdb:forgetful' %}">Forgot Username/Password?</a>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

    <div id="alerts">
        {% if error %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ error }}
                <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                </button>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}

    {% load static %}
    <script src="{% static 'crapdb/js/index.js' %}"></script>

    <script>
        // Sets a global variable with the page error if there is one
        var pageError = "{{ error }}";
        var index_console_output = "{{ index_console_output }}";

        $(document).ready(function() {
            riot.mount("unauth-navbar");
            syncSession();
        });
    </script>
{% endblock %}