rustedbunions/core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
]

rustedbunions/crapdb/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "crapdb"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'admin/$', RedirectView.as_view(url='/admin')),
    url(r'about/$', views.about, name="about"),
    url(r'login/$', views.login, name="login"),
    url(r'forgetful/$', views.forgetful, name="forgetful"),
    url(r'searchcrap/$', views.searchcrap, name="searchcrap"),
    url(r'getpassword/$', views.getpassword, name="getpassword"),
    url(r'main/(?P<session_id>\w+)/$', views.main, name="main"),
    url(r'logout/(?P<session_id>\w+)/$', views.logout, name="logout"),
    url(r'querydb/(?P<session_id>\w+)/$', views.querydb, name="querydb"),
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
    url(r'superadmin/(?P<session_id>\w+)/$', views.super_admin_challenge_get_flag, name="superadmin"),
    url(r'brutalforce/(?P<session_id>\w+)/$', views.brutal_force_challenge_get, name="brutalforce"),
    url(r'brutalforceflag/(?P<session_id>\w+)/$', views.brutal_force_challenge_get_flag, name="brutalforceflag"),
    url(r'rot/(?P<session_id>\w+)/$', views.rot_challenge_get, name="rot"),
    url(r'rotflag/(?P<session_id>\w+)/$', views.rot_challenge_get_flag, name="rotflag"),
    url(r'paidcontent/(?P<session_id>\w+)/$', views.paid_content_challenge_get, name="paidcontent"),
    url(r'paidcontentflag/(?P<session_id>\w+)/$', views.paid_content_challenge_get_flag, name="paidcontentflag"),
    url(r'xor/(?P<session_id>\w+)/$', views.xor_challenge_get, name="xor"),
    url(r'xorflag/(?P<session_id>\w+)/$', views.xor_challenge_get_flag, name="xorflag"),
    url(r'genetic/(?P<session_id>\w+)/$', views.genetic_challenge_get, name="genetic"),
    url(r'geneticflag/(?P<session_id>\w+)/$', views.genetic_challenge_get_flag, name="geneticflag"),
    url(r'syncsession/(?P<session_id>\w+)/$', views.sync_session, name="syncsession"),
]

rustedbunions/leaderboard/urls.py
from django.conf.urls import url
from . import views

app_name = "leaderboard"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'submit/$', views.submit, name="submit"),
    url(r'load/$', views.load, name="load"),
]

rustedbunions/rustedbunions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

index_view = RedirectView.as_view(url="/crapdb/", permanent=True)

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^crapdb/', include('crapdb.urls')),
    url(r'^etc/', include('traveler.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^leaderboard/', include('leaderboard.urls')),
    url(r'^admin/', admin.site.urls),
]

rustedbunions/core/models.py
from django.db import models

class Flag(models.Model):
    '''
    Database model for a flag
    '''
    flag = models.CharField(max_length=100, verbose_name="Flag")
    value = models.IntegerField(default=0, verbose_name="Flag Value")

    def __str__(self):
        return "{} = {}".format(self.flag, self.value)

rustedbunions/core/views.py
import json

from django.shortcuts import redirect, reverse
from django.http import HttpResponse

from .session import Session, UnauthenticatedSession
from .models import Flag
from .util import is_user_data_valid, DataType

class FlagAlreadyClaimedError(Exception):
    pass

def calc_lifetime_hacker_bucks_from_claimed_flags(claimed_flags):
    lifetime_hacker_bucks = 0

    for flag in claimed_flags:
        #pylint: disable=E1101
        flagentry = Flag.objects.filter(flag=flag)
        if flagentry:
            lifetime_hacker_bucks += flagentry[0].value

    return lifetime_hacker_bucks

def update_hacker_bucks_from_flag(session, userflag):
    '''
    Get flag points from the real database. This
    is actually done securely...no SQL injections
    here
    '''

    # Normalize input
    userflag = userflag.strip()
    hacker_bucks = 0
    matched_flag = None

    # Stop here if the flag is too long
    if not is_user_data_valid(userflag, data_type=DataType.FLAG):
        return

    try:
        #pylint: disable=E1101
        for flagentry in Flag.objects.all():
            flag = flagentry.flag

            # Check if it's equal
            if userflag == flag:
                hacker_bucks = flagentry.value
                matched_flag = flag

            # If not, see if they just submitted the flag
            # value b/w curly braces
            pure_flag = flag.replace("flag{", '')
            pure_flag = pure_flag.replace("}", '')
            if userflag == pure_flag:
                hacker_bucks = flagentry.value
                matched_flag = flag
    except:
        pass

    if hacker_bucks and matched_flag:
        # If the flag hasn't already been claimed
        if matched_flag not in session.claimed_flags:
            session.claimed_flags.append(matched_flag)
            session.hacker_bucks += hacker_bucks
            session.lifetime_hacker_bucks += hacker_bucks
        else:
            raise FlagAlreadyClaimedError()

def get_session(session_id, fail_url="crapdb:index",
                error="No session or session expired",
                http_response=False):
    '''
    Returns a tuple of (status, session or redirect)
     - If status is True the second element is a session object
     - If status is False the second element is a django redirect
    '''

    if not is_user_data_valid(session_id, data_type=DataType.OID):
        # WTF is this shit?!
        print("********get_session() - Session ID length - Somebody is messing around*********")
        if not http_response:
            return (False, redirect(reverse(fail_url) + "?error={}".format(error)))
        else:
            return (False, HttpResponse(json.dumps({"redirect": error})))

    session = None
    try:
        session = Session.get_session(session_id)
    except KeyError:
        if not http_response:
            return (False, redirect(reverse(fail_url) + "?error={}".format(error)))
        else:
            return (False, HttpResponse(json.dumps({"redirect": error})))

    return (True, session)

def get_unauth_session(request):
    unauth_session = None

    if "unauth_session" not in request.session:
        unauth_session = UnauthenticatedSession(request=request)
        request.session["unauth_session"] = unauth_session.oid
    else:
        session_id = request.session["unauth_session"]
        if not is_user_data_valid(session_id, data_type=DataType.OID):
            # WTF is this shit?!
            print("********get_unauth_session() - Session ID length - Somebody is messing around*********")
            unauth_session = UnauthenticatedSession(request=request)
            request.session["unauth_session"] = unauth_session.oid
            return unauth_session

        try:
            unauth_session = Session.get_session(request.session["unauth_session"])
        except KeyError:
            unauth_session = UnauthenticatedSession(oid=request.session["unauth_session"], request=request)

    return unauth_session

def checkflag(request, session_id):
    try:
        session = Session.get_session(session_id)
    except KeyError:
        session = UnauthenticatedSession(oid=session_id, request=request)

    ret = {"hacker_bucks": session.hacker_bucks}

    if request.POST:
        d = request.POST.dict()
        flag = d.get("flag", None)

        if flag is not None:
            if not is_user_data_valid(flag, data_type=DataType.FLAG):
                ret["error"] = "Too much data"
            else:
                try:
                    update_hacker_bucks_from_flag(session, flag)
                    ret["hacker_bucks"] = session.hacker_bucks
                except FlagAlreadyClaimedError:
                    ret["error"] = "Already claimed"

    return HttpResponse(json.dumps(ret))

rustedbunions/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

            <meta name="theme-color" content="#4286f4" />

            <title>C4n y0u H4ck 1t</title>

            <!-- Bootstrap CSS -->
            <link
                rel="stylesheet"
                href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                crossorigin="anonymous">

            {% load static %}
            <!-- Handles the favicon -->
            <link rel="shortcut icon" type="image/png" href="{% static 'core/img/favicon.ico' %}"/>

            <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
            <link rel="stylesheet" href="{% static 'core/css/ie10-viewport-bug-workaround.css' %}">

            <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
        {% endblock %}
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}

            <footer class="footer">
                {% block footer %}
                    <p>
                        &copy; {% now "Y" %} rustedbunions.com |
                        <a href="{% url 'crapdb:about' %}">about</a>
                        | <a href="{% url 'leaderboard:index' %}">leaderboard</a>
                    </p>
                {% endblock %}
            </footer>
        </div>

        {% block script %}
            <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous"></script>

            <!-- Popper (necessary for Bootstrap) -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>

            <!-- Bootstrap Javascript -->
            <script
                src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>

            <!-- RIOT JS -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/riot/3.7.3/riot+compiler.min.js"
                integrity="sha256-GHA3LYZISL25HCo1Hu8hAxdb96gNplLLnVDsl0MKamM="
                crossorigin="anonymous"></script>

            <!-- SHA256 Implementation in JS -->
            <script
                src="https://cdnjs.cloudflare.com/ajax/libs/js-sha256/0.8.0/sha256.min.js"
                integrity="sha256-YSPBMepWsRDP0wlRlKhlWUNPbRPPqBiwj3jXEMTdeD8="
                crossorigin="anonymous"></script>

            {% load static %}
            <!-- Load the core JS for the site -->
            <script src="{% static 'core/js/core.js' %}"></script>

            <script>
                // Define these so they can be used to submit flags when not authenticated
                csrf_token = "{{ csrf_token }}";
                unauth_session_oid = "{{ unauth_session.oid }}";
                session_id = "{{ session_id }}";
            </script>
        {% endblock %}
    </body>
</html>