rustedbunions/core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
]

rustedbunions/crapdb/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = "crapdb"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'admin/$', RedirectView.as_view(url='/admin')),
    url(r'about/$', views.about, name="about"),
    url(r'login/$', views.login, name="login"),
    url(r'forgetful/$', views.forgetful, name="forgetful"),
    url(r'searchcrap/$', views.searchcrap, name="searchcrap"),
    url(r'getpassword/$', views.getpassword, name="getpassword"),
    url(r'main/(?P<session_id>\w+)/$', views.main, name="main"),
    url(r'logout/(?P<session_id>\w+)/$', views.logout, name="logout"),
    url(r'querydb/(?P<session_id>\w+)/$', views.querydb, name="querydb"),
    url(r'checkflag/(?P<session_id>\w+)/$', views.checkflag, name="checkflag"),
    url(r'superadmin/(?P<session_id>\w+)/$', views.super_admin_challenge_get_flag, name="superadmin"),
    url(r'brutalforce/(?P<session_id>\w+)/$', views.brutal_force_challenge_get, name="brutalforce"),
    url(r'brutalforceflag/(?P<session_id>\w+)/$', views.brutal_force_challenge_get_flag, name="brutalforceflag"),
    url(r'rot/(?P<session_id>\w+)/$', views.rot_challenge_get, name="rot"),
    url(r'rotflag/(?P<session_id>\w+)/$', views.rot_challenge_get_flag, name="rotflag"),
    url(r'paidcontent/(?P<session_id>\w+)/$', views.paid_content_challenge_get, name="paidcontent"),
    url(r'paidcontentflag/(?P<session_id>\w+)/$', views.paid_content_challenge_get_flag, name="paidcontentflag"),
    url(r'xor/(?P<session_id>\w+)/$', views.xor_challenge_get, name="xor"),
    url(r'xorflag/(?P<session_id>\w+)/$', views.xor_challenge_get_flag, name="xorflag"),
    url(r'genetic/(?P<session_id>\w+)/$', views.genetic_challenge_get, name="genetic"),
    url(r'geneticflag/(?P<session_id>\w+)/$', views.genetic_challenge_get_flag, name="geneticflag"),
    url(r'syncsession/(?P<session_id>\w+)/$', views.sync_session, name="syncsession"),
]

rustedbunions/leaderboard/urls.py
from django.conf.urls import url
from . import views

app_name = "leaderboard"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'submit/$', views.submit, name="submit"),
    url(r'load/$', views.load, name="load"),
]

rustedbunions/rustedbunions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

index_view = RedirectView.as_view(url="/crapdb/", permanent=True)

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^crapdb/', include('crapdb.urls')),
    url(r'^etc/', include('traveler.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^leaderboard/', include('leaderboard.urls')),
    url(r'^admin/', admin.site.urls),
]

rustedbunions/leaderboard/models.py
from django.db import models
from django.utils import timezone

from core.util import ObjectId

class LeaderboardEntry(models.Model):
    '''
    Database model for a leaderboard entry
    '''
    name = models.CharField(max_length=25, verbose_name="Name")
    display_name = models.CharField(default="", max_length=25, verbose_name="Display Name")
    hacker_bucks = models.IntegerField(default=0, verbose_name="Hacker Bucks")
    lifetime_hacker_bucks = models.IntegerField(default=0, verbose_name="Lifetime Hacker Bucks")
    num_flags_found = models.IntegerField(default=0, verbose_name="Number of Flags Found")
    claimed_flags = models.CharField(default="", max_length=4000, verbose_name="List of Claimed Flags")
    playtime = models.CharField(verbose_name="Total Playtime", max_length=25)
    percent_complete = models.IntegerField(default=0, verbose_name="Percent Complete")
    secret_key = models.CharField(default="", max_length=128, verbose_name="Secret Key")
    leader_oid = models.CharField(default=ObjectId, max_length=32, verbose_name="Leader OID")
    session_creation_time = models.DateTimeField(default=timezone.now, verbose_name="Session Creation Time")
    purchased_challenges = models.CharField(default="", max_length=4000, verbose_name="Purchased Challenges")
    remote_ip = models.CharField(default="", max_length=64, verbose_name="Remote IP")
    last_modified = models.DateTimeField(auto_now=True, verbose_name="Last Modified")
    leader_created = models.DateTimeField(auto_now_add=True, verbose_name="Leader Created Time")

    def __str__(self):
        return "{} - {}".format(self.name, self.lifetime_hacker_bucks)

rustedbunions/leaderboard/views.py
import json
import hashlib
from html.parser import HTMLParser

from django.http import HttpResponse
from django.template import loader
from django.utils import timezone

from flags import FlagGenerator
from core.util import is_user_data_valid, DataType
from core.views import get_unauth_session, calc_lifetime_hacker_bucks_from_claimed_flags
from .models import LeaderboardEntry

FLAGS = FlagGenerator.generate_flags()

def get_leaderboard():
    '''
    Get all the entries in the leaderboard
    '''
    try:
        #pylint: disable=E1101
        ret = LeaderboardEntry.objects.order_by("-lifetime_hacker_bucks", "playtime", "-num_flags_found")
        if len(ret) > 50:
            ret = ret[:50]
        return ret
    except:
        return []

def get_leader(name, secret_key=None):
    '''
    Get a specific leader entry to load
    '''
    try:
        #pylint: disable=E1101
        if secret_key:
            ret = LeaderboardEntry.objects.filter(name=name, secret_key=secret_key)
        else:
            ret = LeaderboardEntry.objects.filter(name=name)
        if len(ret) == 1:
            ret = ret[0]
        return ret
    except:
        return None

def index(request):
    context = {
        "unauth_session": get_unauth_session(request).to_json(),
        "leaderboard": get_leaderboard(),
        "num_flags": len(FLAGS)
    }
    template = loader.get_template('leaderboard/index.html')
    return HttpResponse(template.render(context, request))

def load(request):
    ret = {}

    if request.POST:
        d = request.POST.dict()
        name = d.get("name", None)
        secret_key = d.get("secret_key", None)

        if name and secret_key:
            if not is_user_data_valid(name, data_type=DataType.SHORT_NAME):
                ret["error"] = "Too much data"
            elif not is_user_data_valid(secret_key, data_type=DataType.PASSWORD):
                ret["error"] = "Too much data"
            else:
                name = name.strip().lower() # Normalize the name
                session = get_unauth_session(request)
                secret_key = hashlib.sha512(secret_key.encode('utf-8')).hexdigest()
                leader = get_leader(name, secret_key)
                if leader:
                    session.lifetime_hacker_bucks = leader.lifetime_hacker_bucks
                    session.claimed_flags = json.loads(leader.claimed_flags)
                    session.hacker_bucks = leader.hacker_bucks
                    session.creation_time = leader.session_creation_time

                    leader_purchased_challenges = json.loads(leader.purchased_challenges)
                    for challenge_id in leader_purchased_challenges:
                        challenge = session.get_challenge(challenge_id)
                        if challenge:
                            challenge.purchased = True
                else:
                    ret["error"] = "Cannot find leader with the provided name/secret_key combination"
        else:
            ret["error"] = "Invalid POST request. Missing cirtical information"

    return HttpResponse(json.dumps(ret))

def submit(request):
    ret = {}
    has_html = False

    if request.POST:
        d = request.POST.dict()
        name = d.get("name", None)
        secret_key = d.get("secret_key", None)

        if name and is_user_data_valid(name):
            parser = HTMLParser()
            parser.feed(name)
            parser.close()
            if parser.get_starttag_text():
                ret["flag"] = FLAGS["scoreboard_hacking"][0]
                has_html = True

        if name and secret_key and not has_html:
            if not is_user_data_valid(name, data_type=DataType.SHORT_NAME):
                ret["error"] = "Too much data"
            elif not is_user_data_valid(secret_key, data_type=DataType.PASSWORD):
                ret["error"] = "Too much data"
            elif get_leader(name.strip().lower()):
                # If they also proved the correct secret key, update that entry in the database
                secret_key = hashlib.sha512(secret_key.encode('utf-8')).hexdigest()
                leader = get_leader(name.strip().lower(), secret_key)
                if leader:
                    session = get_unauth_session(request)
                    if not session.lifetime_hacker_bucks:
                        ret["error"] = "What makes you think you belong on the leaderboard?"
                    else:
                        # Update the leader with the new info
                        # Create a set of claimed flags and combine the loaded leader with the current session
                        leader_claimed_flags = json.loads(leader.claimed_flags)
                        claimed_flags = list(set(leader_claimed_flags + session.claimed_flags))

                        leader.lifetime_hacker_bucks = calc_lifetime_hacker_bucks_from_claimed_flags(claimed_flags)
                        leader.num_flags_found = len(claimed_flags)
                        leader.claimed_flags = json.dumps(claimed_flags)

                        # This will overwrite their hacker bucks. Only an issue if they didn't load first
                        leader.hacker_bucks = session.hacker_bucks
                        leader.remote_ip = session.remote_ip
                        leader.percent_complete = int((leader.num_flags_found) / len(FLAGS) * 100)
                        leader.playtime = str(timezone.now() - leader.session_creation_time)

                        leader_purchased_challenges = json.loads(leader.purchased_challenges)
                        for challenge_id, challenge in session.challenges.items():
                            if challenge.purchased:
                                leader_purchased_challenges.append(challenge_id)
                        leader_purchased_challenges = list(set(leader_purchased_challenges))
                        leader.purchased_challenges = json.dumps(leader_purchased_challenges)

                        # Update the changes
                        leader.save()
                else:
                    ret["error"] = "Already a leader with that name. To update, provide the correct password."
            else:
                name = name.strip()
                session = get_unauth_session(request)
                if not session.lifetime_hacker_bucks:
                    ret["error"] = "What makes you think you belong on the leaderboard?"
                else:
                    leader = LeaderboardEntry()
                    leader.lifetime_hacker_bucks = session.lifetime_hacker_bucks
                    leader.num_flags_found = len(session.claimed_flags)
                    leader.claimed_flags = json.dumps(session.claimed_flags)
                    leader.hacker_bucks = session.hacker_bucks
                    leader.percent_complete = int((leader.num_flags_found / len(FLAGS)) * 100)
                    leader.name = name.lower()
                    leader.display_name = name
                    leader.remote_ip = session.remote_ip
                    leader.session_creation_time = session.creation_time
                    leader.secret_key = hashlib.sha512(secret_key.encode('utf-8')).hexdigest()
                    leader.playtime = str(timezone.now() - session.creation_time)

                    # Get the list of purchased challenge IDs
                    purchased_challenges = []
                    for challenge_id, challenge in session.challenges.items():
                        if challenge.purchased:
                            purchased_challenges.append(challenge_id)
                    leader.purchased_challenges = json.dumps(purchased_challenges)

                    leader.save()
        elif not has_html:
            ret["error"] = "No name/secret key provided for leaderboard entry"

    return HttpResponse(json.dumps(ret))

rustedbunions/leaderboard/templates/leaderboard/index.html
{% extends 'core/base.html' %}

{% block head %}
    {{ block.super }}

    {% load static %}
    <link href="{% static 'leaderboard/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/unauth-navbar.css' %}" rel="stylesheet">

    <!-- Load Riot Tags -->
    <script src="{% static 'core/tags/unauth-navbar.tag.html' %}" type='riot/tag'></script>
{% endblock %}

{% block content %}
    <unauth-navbar hacker-bucks="{{ unauth_session.hacker_bucks }}"></unauth-navbar>

    <div id="error"></div>

    <p>Provide a nickname and password to save or load your score (score must be greater than 0 to save)</p>

    <form autocomplete="off" class="form-inline col-md-12" onsubmit="submitScore(event)" action="#">
        <!-- Trying my hardest to avoid autocomplete here-->
        <input style="display:none;" autocomplete="false" type="text" name="noautocomplete">
        <input style="display:none" type="text" name="username"/>
        <input style="display:none" type="password" name="password"/>

        <div class="form-group">
            <label for="inputName" class="sr-only">Nickname</label>
            <input type="text" class="form-control" id="inputName" maxlength="25" placeholder="Nickname" required>
        </div>
        <div class="form-group">
            <label for="secretKey" class="sr-only">Password</label>
            <input type="password" autocomplete="new-password" class="form-control" maxlength="128" id="secretKey" placeholder="Password" required>
        </div>
        <div class="form-group">
            <button
                type="submit"
                class="btn btn-primary"
                data-toggle="tooltip"
                data-placement="top"
                title="Save or Update a score">
                Submit/Update Score
            </button>
        </div>
        <div class="form-group">
            <button
                type="button"
                class="btn btn-primary"
                onclick="resumeSession(event)"
                data-toggle="tooltip"
                data-placement="top"
                title="Load an existing session">
                Resume Session
            </button>
        </div>
    </form>

    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Lifetime Hacker Bucks</th>
                <th scope="col">Current Hacker Bucks</th>
                <th scope="col">Total Playtime</th>
                <th scope="col">Flags Found</th>
                <th scope="col">% Complete</th>
            </tr>
        </thead>
        <tbody>
            {% for leader in leaderboard %}
                <tr>
                    <td>{{ leader.display_name }}</td>
                    <td>{{ leader.lifetime_hacker_bucks }}</td>
                    <td>{{ leader.hacker_bucks }}</td>
                    <td>{{ leader.playtime }}</td>
                    <td>{{ leader.num_flags_found }}/{{ num_flags }}</td>
                    <td>
                        <div class="progress" style="height: 20px;">
                            <div class="progress-bar bg-success"
                                role="progressbar" style="width: {{ leader.percent_complete }}%;"
                                aria-valuenow="{{ leader.percent_complete }}" aria-valuemin="0"
                                aria-valuemax="100"></div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if leaderboard|length == 0 %}
        <button class="btn btn-secondary btn-lg btn-block disabled">No Scores</button>
    {% endif %}
    <hr>
{% endblock %}

{% block footer %}
    <p>&copy; {% now "Y" %} rustedbunions.com | <a href="{% url 'crapdb:index' %}">home</a></p>
{% endblock %}

{% block script %}
    {{ block.super }}

    <script>
        function resumeSession(e) {
            var name = $("#inputName").val();
            var secret_key = $("#secretKey").val();

            // Clear on submit
            $("#inputName").val('');
            $("#secretKey").val('');

            $.ajax({
                url: "/leaderboard/load/",
                type: "POST",
                data: {
                    name: name,
                    secret_key: secret_key,
                    csrfmiddlewaretoken: csrf_token
                },
                success: function(data) {
                    var res = JSON.parse(data);

                    if (res.error) {
                        console.log("Failed: ", res.error);
                        errorAlert(res.error, options={
                            target: $("#error")
                        });
                    } else {
                        window.location = "/leaderboard/";
                    }
                }
            });
        }

        function submitScore(e) {
            e.preventDefault(); // Prevent the submit from redirecting automatically

            var name = $("#inputName").val();
            var secret_key = $("#secretKey").val();

            // Clear on submit
            $("#inputName").val('');
            $("#secretKey").val('');

            $.ajax({
                url: "/leaderboard/submit/",
                type: "POST",
                data: {
                    name: name,
                    secret_key: secret_key,
                    csrfmiddlewaretoken: csrf_token
                },
                success: function(data) {
                    var res = JSON.parse(data);

                    if (res.error) {
                        console.log("Failed: ", res.error);
                        errorAlert(res.error, options={
                            target: $("#error")
                        });
                    } else {
                        if (res.flag) {
                            // Alert is blocking
                            alert(res.flag);
                        }
                        // Reload the page
                        window.location = "/leaderboard/";
                    }
                }
            });
        }

        $(document).ready(function() {
            riot.mount("unauth-navbar");
            syncSession();
        });
    </script>
{% endblock %}